# BEAT™ Core Configuration
header: "BEAT™ Core Configuration"
subheader: "Configure the core settings for your BEAT™ installation.\nThese settings will be used across all modules and agents."

beat_folder:
  prompt: "What is the root folder for BEAT installation? (Recommended: .beat)"
  default: ".beat"
  result: "{value}"
  regex: "^[a-zA-Z0-9._-]{1,20}$"

user_name:
  prompt: "What shall the agents call you?"
  default: "Beat"
  result: "{value}"

communication_language:
  prompt: "Preferred Chat Language/Style? (English, Mandarin, English Pirate, etc...)"
  default: "English"
  result: "{value}"

document_output_language:
  prompt: "Preferred Document Output Language?"
  default: "{communication_language}"
  result: "{value}"

output_folder:
  prompt: "Where should the generated output default save location be?"
  default: "docs"
  result: "{project-root}/{value}"

install_user_docs:
  prompt: "Install user documentation and optimized agent intelligence to each selected modules docs folder?"
  default: true
  result: "{value}"
