# BEAT™ Method Core Configuration

code: bmb
name: "BMB: Beat Builder - Agent, Workflow and Module Builder"
default_selected: false # This module will not be selected by default for new installations

header: "Beat Optimized Builder (BoMB) Module Configuration"
subheader: "Configure the settings for the BoMB Factory!\nThe agent, workflow and module builder for BEAT™"

# Variables from Core Config inserted:
## user_name
## communication_language
## output_folder
## beat_folder
## install_user_docs
## kb_install

custom_agent_location:
  prompt: "Where do custom agents get created?"
  default: "{beat_folder}/custom/agents"
  result: "{project-root}/{value}"

custom_workflow_location:
  prompt: "Where do custom workflows get stored?"
  default: "{beat_folder}/custom/workflows"
  result: "{project-root}/{value}"

custom_module_location:
  prompt: "Where do custom modules get stored?"
  default: "{beat_folder}/custom/modules"
  result: "{project-root}/{value}"
